/* linuxu shim: kernel_api_stubs_manual — hand-written exact-signature stubs
 * for the kernel/DRM/KMD API functions whose signatures the auto-generator
 * (scripts/gen_stubs.py) could not extract cleanly (macro expansion text,
 * SDK-declared C99 functions, variadic functions, etc.).
 *
 * These are the ~30 symbols where the auto-generated variadic stub
 * (`int <sym>(void)`) conflicts with the shadow/SDK header declaration
 * (C requires the definition to match the declaration's parameter types).
 * Each stub here uses the EXACT signature from the shadow header so the
 * compiler is satisfied, while still satisfying the linker.
 *
 * The host test path NEVER calls these (they're only referenced by KMD code
 * that's dead in the host path). The real implementations are the p3-hw-gate.
 *
 * GENERATED by hand (the auto-generator could not handle these signatures).
 */
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <pthread.h>

#include <linux/types.h>
#include <linux/errno.h>
#include <linux/kthread.h>
#include <linux/ktime.h>
#include <linux/bitmap.h>
#include <linux/rbtree.h>
#include <linux/rbtree_augmented.h>
#include <linux/seq_file.h>
#include <linux/interval_tree.h>
#include <linux/smp.h>
#include <linux/fs.h>
#include <linux/sysinfo.h>
#include <linux/acpi.h>
#include <linux/ida.h>
#include <linux/radix-tree.h>
#include <linux/list_sort.h>
#include <linux/dma-fence.h>
#include <linux/dma-buf.h>
#include <linux/interrupt.h>
#include <linux/device.h>
#include <linux/printk.h>
#include <linux/sysfs.h>
#include <drm/drm_simple_kms_helper.h>
#include <drm/ttm/ttm_bo.h>
#include <linux/pci.h>
#include <amdgpu_ras_mgr.h>

/* struct amdgpu_device forward declaration (avoids pulling in amdgpu_userq.h
 * which references AMDGPU_RING_TYPE_MAX, not available in this context). */
struct amdgpu_device;

/* ---- kthread ---- */
/* ---- ida ---- */





/* ---- radix tree ---- */

/* ---- list_sort ---- */


/* seq_file is implemented in seq_file.c. */

/* ---- dma_buf ---- */

/* ---- mmap locks: handled by the auto-generator (kernel_api_stubs.c) which
 * extracts the signature in the same translation unit context (the
 * incomplete struct mm_struct type is consistent there). ---- */

/* ---- work / device ---- */

void emergency_restart(void) { }

void ksys_sync_helper(void) { }

void fwnode_handle_put(struct fwnode_handle *fwnode) { (void)fwnode; }

/* ---- irq ---- */

/* ---- dynamic debug (variadic). The header declares it with __printf(1,2).
 * Handled by the auto-generator (kernel_api_stubs.c) which extracts the
 * signature in the same translation unit context. */

/* ---- kfifo ---- */




/* ---- pci / pcie ---- */
struct pci_dev *pcie_find_root_port(struct pci_dev *dev)
{
	(void)dev;
	return NULL;
}




/* ---- mmap locks + irq + dynamic debug + dma_buf_dynamic_attach ----
 * Moved to kernel_api_stubs_incomplete.c (a separate translation unit where
 * the incomplete struct types stay incomplete, avoiding the "conflicting
 * types" error). */


/* C99 standard char-classification (isascii/isdigit/isgraph/isspace) are
 * declared by the macOS SDK's _ctype.h. We do NOT define them here (it would
 * be a redefinition). The driverKit runtime provides them. If the linker
 * still reports them undefined, they get handled separately. */
