/* linuxu shim: kernel_api_stubs - policy-classified kernel API stubs.
 * GENERATED by scripts/gen_stubs.py from linuxu/UNDEFINED_SYMBOLS.txt and
 * scripts/stub_policy.py. Do not edit; change the policy and regenerate:
 *   python3 scripts/gen_stubs.py
 * Each stub names its policy category. `unreachable` stubs log once and
 * return a benign value; no stub returns a negative errno through an
 * unsigned, enum, bool or pointer return type. */
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <pthread.h>

#include <linux/types.h>
#include <linux/errno.h>
#include <linux/printk.h>

#include <linux/kernel.h>
#include <linux/smp.h>
#include <linux/suspend.h>
#include <amdgpu.h>
#include <amdgpu_ras_mgr.h>
#include <drm/drm_crtc.h>
#include <drm/drm_modeset_helper_vtables.h>
#include <drm/drm_privacy_screen_consumer.h>
#include <linux/vgaarb.h>
#include <linux/eventfd.h>
#include <linux/acpi.h>
#include <amdgpu_virt_ras_cmd.h>
#include <drm/display/drm_dp_helper.h>
#include <drm/drm_atomic_helper.h>
#include <drm/drm_atomic_state_helper.h>
#include <drm/drm_crtc_helper.h>
#include <drm/drm_damage_helper.h>
#include <drm/drm_gem_framebuffer_helper.h>
#include <drm/drm_modeset_helper.h>
#include <drm/drm_probe_helper.h>
#include <linux/component.h>
#include <linux/hrtimer.h>
#include <linux/irq.h>
#include <linux/irqdomain.h>
#include <linux/mm.h>
#include <linux/pci.h>
#include <video/cmdline.h>

/* One-shot report for a stub the supported configuration should not reach. */
static void linuxu_stub_unreachable(bool *warned, const char *name)
{
	if (!__atomic_exchange_n(warned, true, __ATOMIC_RELAXED))
		pr_warn("linuxu: unexpected call to unsupported kernel API %s()\n",
			name);
}
#define LINUXU_STUB_UNREACHABLE(name) do {				\
	static bool __linuxu_warned;					\
	linuxu_stub_unreachable(&__linuxu_warned, name);		\
} while (0)

/* data: one CPU online for cpumask iteration */
struct cpumask __cpu_online_mask = { .bits = { 1 } };

/* disabled-inline: CONFIG_ACPI=n ACPICA stub (ACPI_EXTERNAL_RETURN_STATUS) */
acpi_status acpi_get_table(const char *signature, u32 instance, struct acpi_table_header **table)
{
	(void)signature; (void)instance; (void)table;
	return 0x001C; /* AE_NOT_CONFIGURED */
}

/* disabled-inline: CONFIG_ACPI=n ACPICA stub (ACPI_EXTERNAL_RETURN_VOID) */
void acpi_put_table(struct acpi_table_header *table)
{
	(void)table;
}

/* noop: no kernel taint flags in a userspace service */
void add_taint(int taint, int lock)
{
	/* No effect in this environment. */
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_dispatch_interrupt(struct amdgpu_device *adev, struct ras_ih_info *ih_info)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_dispatch_interrupt");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
uint64_t amdgpu_ras_mgr_gen_ras_event_seqno(struct amdgpu_device *adev, enum ras_seqno_type seqno_type)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_gen_ras_event_seqno");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_handle_consumer_interrupt(struct amdgpu_device *adev, void *data)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_handle_consumer_interrupt");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_handle_controller_interrupt(struct amdgpu_device *adev, void *data)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_handle_controller_interrupt");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_handle_fatal_interrupt(struct amdgpu_device *adev, void *data)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_handle_fatal_interrupt");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_handle_ras_cmd(struct amdgpu_device *adev, uint32_t cmd_id, void *input, uint32_t input_size, void *output, uint32_t out_size)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_handle_ras_cmd");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
bool amdgpu_ras_mgr_is_rma(struct amdgpu_device *adev)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_is_rma");
	return false;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_lookup_bad_pages_in_a_row(struct amdgpu_device *adev, uint64_t addr, uint64_t *nps_page_addr, uint32_t max_page_count)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_lookup_bad_pages_in_a_row");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_post_reset(struct amdgpu_device *adev)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_post_reset");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_pre_reset(struct amdgpu_device *adev)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_pre_reset");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_update_ras_ecc(struct amdgpu_device *adev)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_update_ras_ecc");
	return 0;
}

/* unreachable: SR-IOV virtual-function RAS; the DriverKit service is bare metal */
int amdgpu_virt_ras_check_address_validity(struct amdgpu_device *adev, uint64_t address, bool *hit)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_virt_ras_check_address_validity");
	return 0;
}

/* unreachable: SR-IOV virtual-function RAS; the DriverKit service is bare metal */
int amdgpu_virt_ras_convert_retired_address(struct amdgpu_device *adev, uint64_t address, uint64_t *pfn, uint32_t max_pfn_sz)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_virt_ras_convert_retired_address");
	return 0;
}

/* unreachable: SR-IOV virtual-function RAS; the DriverKit service is bare metal */
void amdgpu_virt_ras_set_remote_uniras(struct amdgpu_device *adev, bool en)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_virt_ras_set_remote_uniras");
}

/* ok-zero: no aggregate master ever binds; Linux component_add() also returns 0 when no master is waiting */
int component_add(struct device *dev, const struct component_ops *ops)
{
	return 0;
}

/* noop: pairs with component_add(); nothing registered */
void component_del(struct device *dev, const struct component_ops *ops)
{
	/* No effect in this environment. */
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_atomic_helper_check(struct drm_device *dev, struct drm_atomic_state *state)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_check");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_atomic_helper_check_plane_state(struct drm_plane_state *plane_state, const struct drm_crtc_state *crtc_state, int min_scale, int max_scale, bool can_position, bool can_update_disabled)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_check_plane_state");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_atomic_helper_commit(struct drm_device *dev, struct drm_atomic_state *state, bool nonblock)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_commit");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_atomic_helper_connector_destroy_state(struct drm_connector *connector, struct drm_connector_state *state)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_connector_destroy_state");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
struct drm_connector_state * drm_atomic_helper_connector_duplicate_state(struct drm_connector *connector)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_connector_duplicate_state");
	return NULL;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_atomic_helper_connector_reset(struct drm_connector *connector)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_connector_reset");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_atomic_helper_crtc_destroy_state(struct drm_crtc *crtc, struct drm_crtc_state *state)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_crtc_destroy_state");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
struct drm_crtc_state * drm_atomic_helper_crtc_duplicate_state(struct drm_crtc *crtc)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_crtc_duplicate_state");
	return NULL;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_atomic_helper_crtc_reset(struct drm_crtc *crtc)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_crtc_reset");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_atomic_helper_dirtyfb(struct drm_framebuffer *fb, struct drm_file *file_priv, unsigned int flags, unsigned int color, struct drm_clip_rect *clips, unsigned int num_clips)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_dirtyfb");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_atomic_helper_disable_plane(struct drm_plane *plane, struct drm_modeset_acquire_ctx *ctx)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_disable_plane");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_atomic_helper_page_flip(struct drm_crtc *crtc, struct drm_framebuffer *fb, struct drm_pending_vblank_event *event, uint32_t flags, struct drm_modeset_acquire_ctx *ctx)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_page_flip");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_atomic_helper_plane_destroy_state(struct drm_plane *plane, struct drm_plane_state *state)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_plane_destroy_state");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
struct drm_plane_state * drm_atomic_helper_plane_duplicate_state(struct drm_plane *plane)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_plane_duplicate_state");
	return NULL;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_atomic_helper_plane_reset(struct drm_plane *plane)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_plane_reset");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_atomic_helper_set_config(struct drm_mode_set *set, struct drm_modeset_acquire_ctx *ctx)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_set_config");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_atomic_helper_shutdown(struct drm_device *dev)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_shutdown");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_atomic_helper_update_plane(struct drm_plane *plane, struct drm_crtc *crtc, struct drm_framebuffer *fb, int crtc_x, int crtc_y, unsigned int crtc_w, unsigned int crtc_h, uint32_t src_x, uint32_t src_y, uint32_t src_w, uint32_t src_h, struct drm_modeset_acquire_ctx *ctx)
{
	LINUXU_STUB_UNREACHABLE("drm_atomic_helper_update_plane");
	return 0;
}

/* disabled-inline: unconditional upstream inline (stores the helper vtable) */
void drm_crtc_helper_add(struct drm_crtc *crtc, const struct drm_crtc_helper_funcs *funcs)
{
	crtc->helper_private = funcs;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_crtc_helper_set_config(struct drm_mode_set *set, struct drm_modeset_acquire_ctx *ctx)
{
	LINUXU_STUB_UNREACHABLE("drm_crtc_helper_set_config");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_crtc_helper_set_mode(struct drm_crtc *crtc, const struct drm_display_mode *mode, int x, int y, struct drm_framebuffer *old_fb)
{
	LINUXU_STUB_UNREACHABLE("drm_crtc_helper_set_mode");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_crtc_init(struct drm_device *dev, struct drm_crtc *crtc, const struct drm_crtc_funcs *funcs)
{
	LINUXU_STUB_UNREACHABLE("drm_crtc_init");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_dp_aux_init(struct drm_dp_aux *aux)
{
	LINUXU_STUB_UNREACHABLE("drm_dp_aux_init");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_dp_aux_register(struct drm_dp_aux *aux)
{
	LINUXU_STUB_UNREACHABLE("drm_dp_aux_register");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_dp_aux_unregister(struct drm_dp_aux *aux)
{
	LINUXU_STUB_UNREACHABLE("drm_dp_aux_unregister");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
ssize_t drm_dp_dpcd_read(struct drm_dp_aux *aux, unsigned int offset, void *val, size_t size)
{
	LINUXU_STUB_UNREACHABLE("drm_dp_dpcd_read");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_dp_dpcd_read_link_status(struct drm_dp_aux *aux, u8 *link_status)
{
	LINUXU_STUB_UNREACHABLE("drm_dp_dpcd_read_link_status");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
ssize_t drm_dp_dpcd_write(struct drm_dp_aux *aux, unsigned int offset, const void *val, size_t size)
{
	LINUXU_STUB_UNREACHABLE("drm_dp_dpcd_write");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_dp_set_subconnector_property(struct drm_connector *connector, enum drm_connector_status status, const u8 *dpcd, const u8 *downstream_ports)
{
	LINUXU_STUB_UNREACHABLE("drm_dp_set_subconnector_property");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_gem_fb_create_handle(struct drm_framebuffer *fb, struct drm_file *file, unsigned int *handle)
{
	LINUXU_STUB_UNREACHABLE("drm_gem_fb_create_handle");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_gem_fb_destroy(struct drm_framebuffer *fb)
{
	LINUXU_STUB_UNREACHABLE("drm_gem_fb_destroy");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
struct drm_gem_object * drm_gem_fb_get_obj(struct drm_framebuffer *fb, unsigned int plane)
{
	LINUXU_STUB_UNREACHABLE("drm_gem_fb_get_obj");
	return NULL;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
int drm_helper_connector_dpms(struct drm_connector *connector, int mode)
{
	LINUXU_STUB_UNREACHABLE("drm_helper_connector_dpms");
	return 0;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_helper_force_disable_all(struct drm_device *dev)
{
	LINUXU_STUB_UNREACHABLE("drm_helper_force_disable_all");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
bool drm_helper_hpd_irq_event(struct drm_device *dev)
{
	LINUXU_STUB_UNREACHABLE("drm_helper_hpd_irq_event");
	return false;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_helper_mode_fill_fb_struct(struct drm_device *dev, struct drm_framebuffer *fb, const struct drm_format_info *info, const struct drm_mode_fb_cmd2 *mode_cmd)
{
	LINUXU_STUB_UNREACHABLE("drm_helper_mode_fill_fb_struct");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_kms_helper_hotplug_event(struct drm_device *dev)
{
	LINUXU_STUB_UNREACHABLE("drm_kms_helper_hotplug_event");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
bool drm_kms_helper_is_poll_worker(void)
{
	LINUXU_STUB_UNREACHABLE("drm_kms_helper_is_poll_worker");
	return false;
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_kms_helper_poll_disable(struct drm_device *dev)
{
	LINUXU_STUB_UNREACHABLE("drm_kms_helper_poll_disable");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_kms_helper_poll_enable(struct drm_device *dev)
{
	LINUXU_STUB_UNREACHABLE("drm_kms_helper_poll_enable");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_kms_helper_poll_fini(struct drm_device *dev)
{
	LINUXU_STUB_UNREACHABLE("drm_kms_helper_poll_fini");
}

/* unreachable: compute profile: CONFIG_DRM_AMD_DC=n, no legacy DCE or virtual display IP is added for supported ASICs, so mode setting never initializes */
void drm_kms_helper_poll_init(struct drm_device *dev)
{
	LINUXU_STUB_UNREACHABLE("drm_kms_helper_poll_init");
}

/* disabled-inline: CONFIG_DRM_PRIVACY_SCREEN=n */
void drm_privacy_screen_put(struct drm_privacy_screen *priv)
{

}

/* disabled-inline: CONFIG_EVENTFD=n; eventfd_ctx_fdget() never hands out a context */
void eventfd_ctx_put(struct eventfd_ctx *ctx)
{

}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs */
irqreturn_t handle_simple_irq(int irq, void *dev_id)
{
	LINUXU_STUB_UNREACHABLE("handle_simple_irq");
	return IRQ_NONE;
}

/* unreachable: hrtimer only drives the amdgpu_vkms virtual-display vblank */
bool hrtimer_active(const struct hrtimer *timer)
{
	LINUXU_STUB_UNREACHABLE("hrtimer_active");
	return false;
}

/* unreachable: hrtimer only drives the amdgpu_vkms virtual-display vblank; 0 = timer was not active */
int hrtimer_cancel(struct hrtimer *timer)
{
	LINUXU_STUB_UNREACHABLE("hrtimer_cancel");
	return 0;
}

/* unreachable: hrtimer only drives the amdgpu_vkms virtual-display vblank */
ktime_t hrtimer_cb_get_time(const struct hrtimer *timer)
{
	LINUXU_STUB_UNREACHABLE("hrtimer_cb_get_time");
	return 0;
}

/* unreachable: hrtimer only drives the amdgpu_vkms virtual-display vblank; 0 overruns */
u64 hrtimer_forward(struct hrtimer *timer, ktime_t now, ktime_t interval)
{
	LINUXU_STUB_UNREACHABLE("hrtimer_forward");
	return 0;
}

/* unreachable: hrtimer only drives the amdgpu_vkms virtual-display vblank */
void hrtimer_setup(struct hrtimer *timer, enum hrtimer_restart (*function)(struct hrtimer *), clockid_t clock_id, enum hrtimer_mode mode)
{
	LINUXU_STUB_UNREACHABLE("hrtimer_setup");
}

/* unreachable: hrtimer only drives the amdgpu_vkms virtual-display vblank */
void hrtimer_start_range_ns(struct hrtimer *timer, ktime_t tim, u64 range_ns, const enum hrtimer_mode mode)
{
	LINUXU_STUB_UNREACHABLE("hrtimer_start_range_ns");
}

/* unreachable: hrtimer only drives the amdgpu_vkms virtual-display vblank; 0 = timer was not active */
int hrtimer_try_to_cancel(struct hrtimer *timer)
{
	LINUXU_STUB_UNREACHABLE("hrtimer_try_to_cancel");
	return 0;
}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs; 0 = no mapping */
int irq_create_mapping(struct irq_domain *d, irq_hw_number_t hwirq)
{
	LINUXU_STUB_UNREACHABLE("irq_create_mapping");
	return 0;
}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs; NULL makes amdgpu_irq_add_domain() fail cleanly */
struct irq_domain * irq_domain_create_linear(struct device_node *of_node, unsigned int size, const struct irq_domain_ops *ops, void *arg)
{
	LINUXU_STUB_UNREACHABLE("irq_domain_create_linear");
	return NULL;
}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs */
void irq_domain_remove(struct irq_domain *d)
{
	LINUXU_STUB_UNREACHABLE("irq_domain_remove");
}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs */
void irq_set_chip_and_handler(int irq, struct irq_chip *chip, irq_handler_t handler)
{
	LINUXU_STUB_UNREACHABLE("irq_set_chip_and_handler");
}

/* data: MP0 13.0.6/12/14 only; a named block without callbacks keeps amdgpu_device_ip_block_add() and the IP walkers from dereferencing a NULL funcs table */
static const struct amd_ip_funcs ras_v1_0_unsupported_funcs = {
	.name = "ras_v1_0 (unsupported)",
};
const struct amdgpu_ip_block_version ras_v1_0_ip_block = {
	.type = AMD_IP_BLOCK_TYPE_RAS,
	.major = 1,
	.minor = 0,
	.rev = 0,
	.funcs = &ras_v1_0_unsupported_funcs,
};

/* data: never equals a shutdown state; the shim's SYSTEM_* numbering differs from Linux enum system_states */
int system_state = 0;

/* noop: no Linux CPU page tables map BO address spaces; DriverKit client mappings are owned by the dext memory descriptors */
void unmap_mapping_range(struct address_space *mapping, unsigned long start, unsigned long end, int even_munmap)
{
	/* No effect in this environment. */
}

/* disabled-inline: CONFIG_VGA_ARB=n */
int vga_client_register(struct pci_dev *pdev, unsigned int (*set_decode)(struct pci_dev *pdev, bool state))
{
	return 0;
}

/* disabled-inline: upstream inline wrapper over vga_client_register() */
void vga_client_unregister(struct pci_dev *pdev)
{
	vga_client_register(pdev, NULL);
}

/* ok-zero: no kernel command line, so no video= option exists */
const char * video_get_options(const char *name)
{
	return NULL;
}

/* unreachable: only kfd_process_init_cwsr_apu() (APU CWSR trap area); the IS_ERR_VALUE() error makes KFD fail the APU mmap instead of copying the trap handler through a NULL kernel address */
unsigned long vm_mmap(struct file *file, unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags, unsigned long offset)
{
	LINUXU_STUB_UNREACHABLE("vm_mmap");
	return -ENODEV;
}
