/* linuxu shim: kernel_api_stubs - policy-classified kernel API stubs.
 * GENERATED by scripts/gen_stubs.py from linuxu/UNDEFINED_SYMBOLS.txt and
 * scripts/stub_policy.py. Do not edit; change the policy and regenerate:
 *   python3 scripts/gen_stubs.py
 * Each stub names its policy category. `unreachable` stubs log once and
 * return a benign value; no stub returns a negative errno through an
 * unsigned, enum, bool or pointer return type. */
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <pthread.h>

#include <linux/types.h>
#include <linux/errno.h>
#include <linux/printk.h>

#include <linux/kernel.h>
#include <linux/smp.h>
#include <linux/suspend.h>
#include <amdgpu.h>
#include <amdgpu_ras_mgr.h>
#include <drm/drm_crtc.h>
#include <drm/drm_modeset_helper_vtables.h>
#include <drm/drm_privacy_screen_consumer.h>
#include <linux/vgaarb.h>
#include <linux/eventfd.h>
#include <linux/acpi.h>
#include <amdgpu_virt_ras_cmd.h>
#include <linux/component.h>
#include <linux/irq.h>
#include <linux/irqdomain.h>
#include <linux/mm.h>
#include <linux/pci.h>
#include <video/cmdline.h>

/* One-shot report for a stub the supported configuration should not reach. */
static void linuxu_stub_unreachable(bool *warned, const char *name)
{
	if (!__atomic_exchange_n(warned, true, __ATOMIC_RELAXED))
		pr_warn("linuxu: unexpected call to unsupported kernel API %s()\n",
			name);
}
#define LINUXU_STUB_UNREACHABLE(name) do {				\
	static bool __linuxu_warned;					\
	linuxu_stub_unreachable(&__linuxu_warned, name);		\
} while (0)

/* data: one CPU online for cpumask iteration */
struct cpumask __cpu_online_mask = { .bits = { 1 } };

/* disabled-inline: CONFIG_ACPI=n ACPICA stub (ACPI_EXTERNAL_RETURN_STATUS) */
acpi_status acpi_get_table(const char *signature, u32 instance, struct acpi_table_header **table)
{
	(void)signature; (void)instance; (void)table;
	return 0x001C; /* AE_NOT_CONFIGURED */
}

/* disabled-inline: CONFIG_ACPI=n ACPICA stub (ACPI_EXTERNAL_RETURN_VOID) */
void acpi_put_table(struct acpi_table_header *table)
{
	(void)table;
}

/* noop: no kernel taint flags in a userspace service */
void add_taint(int taint, int lock)
{
	/* No effect in this environment. */
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_dispatch_interrupt(struct amdgpu_device *adev, struct ras_ih_info *ih_info)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_dispatch_interrupt");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
uint64_t amdgpu_ras_mgr_gen_ras_event_seqno(struct amdgpu_device *adev, enum ras_seqno_type seqno_type)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_gen_ras_event_seqno");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_handle_consumer_interrupt(struct amdgpu_device *adev, void *data)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_handle_consumer_interrupt");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_handle_controller_interrupt(struct amdgpu_device *adev, void *data)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_handle_controller_interrupt");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_handle_fatal_interrupt(struct amdgpu_device *adev, void *data)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_handle_fatal_interrupt");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_handle_ras_cmd(struct amdgpu_device *adev, uint32_t cmd_id, void *input, uint32_t input_size, void *output, uint32_t out_size)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_handle_ras_cmd");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
bool amdgpu_ras_mgr_is_rma(struct amdgpu_device *adev)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_is_rma");
	return false;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_lookup_bad_pages_in_a_row(struct amdgpu_device *adev, uint64_t addr, uint64_t *nps_page_addr, uint32_t max_page_count)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_lookup_bad_pages_in_a_row");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_post_reset(struct amdgpu_device *adev)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_post_reset");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_pre_reset(struct amdgpu_device *adev)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_pre_reset");
	return 0;
}

/* unreachable: unified RAS manager (ras/ tree) is deferred; callers are gated by amdgpu_uniras_enabled(), false in ras_policy.c, or belong to unsupported GFX/GMC 12.1 interrupt sources */
int amdgpu_ras_mgr_update_ras_ecc(struct amdgpu_device *adev)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_ras_mgr_update_ras_ecc");
	return 0;
}

/* unreachable: SR-IOV virtual-function RAS; the DriverKit service is bare metal */
int amdgpu_virt_ras_check_address_validity(struct amdgpu_device *adev, uint64_t address, bool *hit)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_virt_ras_check_address_validity");
	return 0;
}

/* unreachable: SR-IOV virtual-function RAS; the DriverKit service is bare metal */
int amdgpu_virt_ras_convert_retired_address(struct amdgpu_device *adev, uint64_t address, uint64_t *pfn, uint32_t max_pfn_sz)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_virt_ras_convert_retired_address");
	return 0;
}

/* unreachable: SR-IOV virtual-function RAS; the DriverKit service is bare metal */
void amdgpu_virt_ras_set_remote_uniras(struct amdgpu_device *adev, bool en)
{
	LINUXU_STUB_UNREACHABLE("amdgpu_virt_ras_set_remote_uniras");
}

/* ok-zero: no aggregate master ever binds; Linux component_add() also returns 0 when no master is waiting */
int component_add(struct device *dev, const struct component_ops *ops)
{
	return 0;
}

/* noop: pairs with component_add(); nothing registered */
void component_del(struct device *dev, const struct component_ops *ops)
{
	/* No effect in this environment. */
}

/* disabled-inline: CONFIG_EVENTFD=n; eventfd_ctx_fdget() never hands out a context */
void eventfd_ctx_put(struct eventfd_ctx *ctx)
{

}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs */
irqreturn_t handle_simple_irq(int irq, void *dev_id)
{
	LINUXU_STUB_UNREACHABLE("handle_simple_irq");
	return IRQ_NONE;
}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs; 0 = no mapping */
int irq_create_mapping(struct irq_domain *d, irq_hw_number_t hwirq)
{
	LINUXU_STUB_UNREACHABLE("irq_create_mapping");
	return 0;
}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs; NULL makes amdgpu_irq_add_domain() fail cleanly */
struct irq_domain * irq_domain_create_linear(struct device_node *of_node, unsigned int size, const struct irq_domain_ops *ops, void *arg)
{
	LINUXU_STUB_UNREACHABLE("irq_domain_create_linear");
	return NULL;
}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs */
void irq_domain_remove(struct irq_domain *d)
{
	LINUXU_STUB_UNREACHABLE("irq_domain_remove");
}

/* unreachable: Linux irq_domain for ACP/ISP child devices (both =n) and the ih_v6_1 APU path; not used by supported dGPUs */
void irq_set_chip_and_handler(int irq, struct irq_chip *chip, irq_handler_t handler)
{
	LINUXU_STUB_UNREACHABLE("irq_set_chip_and_handler");
}

/* data: MP0 13.0.6/12/14 only; a named block without callbacks keeps amdgpu_device_ip_block_add() and the IP walkers from dereferencing a NULL funcs table */
static const struct amd_ip_funcs ras_v1_0_unsupported_funcs = {
	.name = "ras_v1_0 (unsupported)",
};
const struct amdgpu_ip_block_version ras_v1_0_ip_block = {
	.type = AMD_IP_BLOCK_TYPE_RAS,
	.major = 1,
	.minor = 0,
	.rev = 0,
	.funcs = &ras_v1_0_unsupported_funcs,
};

/* data: never equals a shutdown state; the shim's SYSTEM_* numbering differs from Linux enum system_states */
int system_state = 0;

/* noop: no Linux CPU page tables map BO address spaces; DriverKit client mappings are owned by the dext memory descriptors */
void unmap_mapping_range(struct address_space *mapping, unsigned long start, unsigned long end, int even_munmap)
{
	/* No effect in this environment. */
}

/* disabled-inline: CONFIG_VGA_ARB=n */
int vga_client_register(struct pci_dev *pdev, unsigned int (*set_decode)(struct pci_dev *pdev, bool state))
{
	return 0;
}

/* disabled-inline: upstream inline wrapper over vga_client_register() */
void vga_client_unregister(struct pci_dev *pdev)
{
	vga_client_register(pdev, NULL);
}

/* ok-zero: no kernel command line, so no video= option exists */
const char * video_get_options(const char *name)
{
	return NULL;
}

/* unreachable: only kfd_process_init_cwsr_apu() (APU CWSR trap area); the IS_ERR_VALUE() error makes KFD fail the APU mmap instead of copying the trap handler through a NULL kernel address */
unsigned long vm_mmap(struct file *file, unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags, unsigned long offset)
{
	LINUXU_STUB_UNREACHABLE("vm_mmap");
	return -ENODEV;
}
