# mk/upstream_sources.mk
#
# The upstream Linux sources this project compiles, as paths relative to the
# pinned submodule (LINUX, third_party/linux). Nothing is globbed: the
# submodule holds many files the build does not use. The list covers the
# amdgpu, amdkfd, amdxcp, pm and ras trees, TTM, the scheduler and the DRM
# core files amdgpu needs, minus the CONFIG-disabled or deferred files named
# by EXCLUDED_FILES in mk/kernel_config.mk. Object files keep the driver/
# layout under build/:
#   drivers/gpu/drm/amd/<dir>/  -> build/driver/<dir>/
#   drivers/gpu/drm/ttm/        -> build/driver/ttm/
#   drivers/gpu/drm/scheduler/  -> build/driver/scheduler/
#   drivers/gpu/drm/*.c         -> build/driver/drm-core/

LINUX := third_party/linux

UPSTREAM_DRIVER_SRCS := \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/aldebaran.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/aldebaran_reg_init.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_aca.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_afmt.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_aldebaran.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_arcturus.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_fence.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gc_9_4_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gfx_v10.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gfx_v10_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gfx_v11.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gfx_v12.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gfx_v12_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gfx_v8.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gfx_v9.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gpuvm.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_atombios.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_atomfirmware.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_benchmark.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_bios.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_cgs.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_connectors.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_cper.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_cs.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_csa.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ctx.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_debugfs.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_dev_coredump.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_device.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_discovery.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_display.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_dma_buf.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_doorbell_mgr.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_eeprom.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_encoders.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_eviction_fence.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_fence.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_fru_eeprom.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_fw_attestation.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_gart.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_gem.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_gfx.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_gmc.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_gtt_mgr.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_hdp.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_hmm.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_i2c.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ib.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ids.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ih.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ip.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_irq.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_job.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_jpeg.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_kms.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_lsdma.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_mca.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_mes.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_mmhub.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_nbio.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_object.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_pll.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_preempt_mgr.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_psp.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_psp_ta.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_rap.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ras.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ras_eeprom.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_reg_access.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_reset.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ring.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ring_mux.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_rlc.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_sa.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_sched.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_sdma.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_securedisplay.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_seq64.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_sync.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_trace_points.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ttm.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_ucode.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_umc.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_umsch_mm.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_userq.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_userq_fence.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_uvd.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vce.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vcn.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vf_error.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_virt.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vkms.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vm.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vm_cpu.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vm_pt.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vm_sdma.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vm_tlb_fence.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vpe.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_vram_mgr.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_xcp.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/amdgpu_xgmi.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/aqua_vanjaram.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/arct_reg_init.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/athub_v1_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/athub_v2_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/athub_v2_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/athub_v3_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/athub_v4_1_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/atom.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/atombios_crtc.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/atombios_dp.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/atombios_encoders.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/atombios_i2c.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/cyan_skillfish_reg_init.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/cz_ih.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/dce_v10_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/df_v1_7.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/df_v3_6.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/df_v4_15.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/df_v4_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/df_v4_6_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/emu_soc.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v10_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v11_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v11_0_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v12_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v12_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v8_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v9_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v9_4.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v9_4_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfx_v9_4_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v11_5_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v12_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v12_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v1_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v1_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v1_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v2_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v2_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v3_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gfxhub_v3_0_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gmc_v10_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gmc_v11_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gmc_v12_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gmc_v12_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gmc_v7_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gmc_v8_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/gmc_v9_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/hdp_v4_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/hdp_v5_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/hdp_v5_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/hdp_v6_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/hdp_v7_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/iceland_ih.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/ih_v6_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/ih_v6_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/ih_v7_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/imu_v11_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/imu_v11_0_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/imu_v12_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/imu_v12_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v1_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v2_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v2_5.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v3_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v4_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v4_0_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v4_0_5.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v5_0_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v5_0_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v5_0_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/jpeg_v5_3_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/lsdma_v6_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/lsdma_v7_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/lsdma_v7_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mca_v3_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mes_userqueue.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mes_v11_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mes_v12_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mes_v12_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v1_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v1_7.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v1_8.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v2_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v2_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v3_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v3_0_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v3_0_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v3_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v4_1_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v4_2_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mmhub_v9_4.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mxgpu_ai.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mxgpu_nv.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/mxgpu_vi.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/navi10_ih.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbif_v6_3_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbio_v2_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbio_v4_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbio_v6_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbio_v7_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbio_v7_11.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbio_v7_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbio_v7_4.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbio_v7_7.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nbio_v7_9.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/nv.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v10_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v11_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v11_0_8.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v12_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v13_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v13_0_4.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v14_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v15_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v15_0_8.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/psp_v3_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v2_4.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v3_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v4_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v4_4.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v4_4_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v5_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v5_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v6_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v7_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sdma_v7_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/sienna_cichlid.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smu_v11_0_i2c.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smu_v13_0_10.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smuio_v11_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smuio_v11_0_6.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smuio_v13_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smuio_v13_0_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smuio_v13_0_6.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smuio_v14_0_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smuio_v15_0_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smuio_v15_0_8.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/smuio_v9_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/soc15.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/soc21.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/soc24.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/soc_v1_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/tonga_ih.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/umc_v12_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/umc_v6_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/umc_v6_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/umc_v6_7.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/umc_v8_10.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/umc_v8_14.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/umc_v8_7.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/umsch_mm_v4_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/uvd_v5_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/uvd_v6_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/uvd_v7_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vce_v3_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vce_v4_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_sw_ring.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v1_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v2_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v2_5.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v3_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v4_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v4_0_3.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v4_0_5.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v5_0_0.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v5_0_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vcn_v5_0_2.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vega10_ih.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vega10_reg_init.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vega20_ih.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vega20_reg_init.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vi.c \
	$(LINUX)/drivers/gpu/drm/amd/amdgpu/vpe_v6_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/cik_event_interrupt.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_chardev.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_crat.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_debug.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_debugfs.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_device.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_device_queue_manager.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_device_queue_manager_cik.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_device_queue_manager_v10.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_device_queue_manager_v11.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_device_queue_manager_v12.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_device_queue_manager_v12_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_device_queue_manager_v9.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_device_queue_manager_vi.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_doorbell.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_events.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_flat_memory.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_int_process_v10.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_int_process_v11.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_int_process_v12_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_int_process_v9.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_interrupt.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_kernel_queue.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_module.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_mqd_manager.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_mqd_manager_cik.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_mqd_manager_v10.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_mqd_manager_v11.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_mqd_manager_v12.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_mqd_manager_v12_1.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_mqd_manager_v9.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_mqd_manager_vi.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_packet_manager.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_packet_manager_v9.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_packet_manager_vi.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_process.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_process_queue_manager.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_queue.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_smi_events.c \
	$(LINUX)/drivers/gpu/drm/amd/amdkfd/kfd_topology.c \
	$(LINUX)/drivers/gpu/drm/amd/amdxcp/amdgpu_xcp_drv.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/amdgpu_dpm.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/amdgpu_dpm_internal.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/amdgpu_pm.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/legacy-dpm/kv_dpm.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/legacy-dpm/kv_smc.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/legacy-dpm/legacy_dpm.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/legacy-dpm/si_dpm.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/legacy-dpm/si_smc.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/amd_powerplay.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/ci_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/common_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/fiji_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/hardwaremanager.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/hwmgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/polaris_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/pp_overdriver.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/pp_psm.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/ppatomctrl.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/ppatomfwctrl.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/pppcielanes.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/process_pptables_v1_0.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/processpptables.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu10_hwmgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu7_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu7_clockpowergating.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu7_hwmgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu7_powertune.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu7_thermal.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu8_hwmgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu9_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu_helper.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/tonga_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega10_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega10_hwmgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega10_powertune.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega10_processpptables.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega10_thermal.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega12_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega12_hwmgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega12_processpptables.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega12_thermal.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega20_baco.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega20_hwmgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega20_powertune.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega20_processpptables.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega20_thermal.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/ci_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/fiji_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/iceland_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/polaris10_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/smu10_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/smu7_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/smu8_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/smu9_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/tonga_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/vega10_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/vega12_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/vega20_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/powerplay/smumgr/vegam_smumgr.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/amdgpu_smu.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu11/arcturus_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu11/cyan_skillfish_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu11/navi10_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu11/sienna_cichlid_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu11/smu_v11_0.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu11/vangogh_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu12/renoir_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu12/smu_v12_0.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu13/aldebaran_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu13/smu_v13_0.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu13/smu_v13_0_0_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu13/smu_v13_0_12_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu13/smu_v13_0_4_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu13/smu_v13_0_5_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu13/smu_v13_0_6_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu13/smu_v13_0_7_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu13/yellow_carp_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu14/smu_v14_0.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu14/smu_v14_0_0_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu14/smu_v14_0_2_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu15/smu_v15_0.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu15/smu_v15_0_0_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu15/smu_v15_0_8_ppt.c \
	$(LINUX)/drivers/gpu/drm/amd/pm/swsmu/smu_cmn.c \
	$(LINUX)/drivers/gpu/drm/drm_atomic.c \
	$(LINUX)/drivers/gpu/drm/drm_atomic_uapi.c \
	$(LINUX)/drivers/gpu/drm/drm_auth.c \
	$(LINUX)/drivers/gpu/drm/drm_blend.c \
	$(LINUX)/drivers/gpu/drm/drm_bridge.c \
	$(LINUX)/drivers/gpu/drm/drm_cache.c \
	$(LINUX)/drivers/gpu/drm/drm_client.c \
	$(LINUX)/drivers/gpu/drm/drm_client_event.c \
	$(LINUX)/drivers/gpu/drm/drm_client_modeset.c \
	$(LINUX)/drivers/gpu/drm/drm_client_sysrq.c \
	$(LINUX)/drivers/gpu/drm/drm_color_mgmt.c \
	$(LINUX)/drivers/gpu/drm/drm_colorop.c \
	$(LINUX)/drivers/gpu/drm/drm_connector.c \
	$(LINUX)/drivers/gpu/drm/drm_crtc.c \
	$(LINUX)/drivers/gpu/drm/drm_debugfs.c \
	$(LINUX)/drivers/gpu/drm/drm_debugfs_crc.c \
	$(LINUX)/drivers/gpu/drm/drm_displayid.c \
	$(LINUX)/drivers/gpu/drm/drm_drv.c \
	$(LINUX)/drivers/gpu/drm/drm_dumb_buffers.c \
	$(LINUX)/drivers/gpu/drm/drm_edid.c \
	$(LINUX)/drivers/gpu/drm/drm_eld.c \
	$(LINUX)/drivers/gpu/drm/drm_encoder.c \
	$(LINUX)/drivers/gpu/drm/drm_file.c \
	$(LINUX)/drivers/gpu/drm/drm_fourcc.c \
	$(LINUX)/drivers/gpu/drm/drm_framebuffer.c \
	$(LINUX)/drivers/gpu/drm/drm_gem.c \
	$(LINUX)/drivers/gpu/drm/drm_gem_ttm_helper.c \
	$(LINUX)/drivers/gpu/drm/drm_ioctl.c \
	$(LINUX)/drivers/gpu/drm/drm_lease.c \
	$(LINUX)/drivers/gpu/drm/drm_managed.c \
	$(LINUX)/drivers/gpu/drm/drm_mm.c \
	$(LINUX)/drivers/gpu/drm/drm_mode_config.c \
	$(LINUX)/drivers/gpu/drm/drm_mode_object.c \
	$(LINUX)/drivers/gpu/drm/drm_modes.c \
	$(LINUX)/drivers/gpu/drm/drm_modeset_lock.c \
	$(LINUX)/drivers/gpu/drm/drm_pci.c \
	$(LINUX)/drivers/gpu/drm/drm_plane.c \
	$(LINUX)/drivers/gpu/drm/drm_prime.c \
	$(LINUX)/drivers/gpu/drm/drm_print.c \
	$(LINUX)/drivers/gpu/drm/drm_property.c \
	$(LINUX)/drivers/gpu/drm/drm_rect.c \
	$(LINUX)/drivers/gpu/drm/drm_suballoc.c \
	$(LINUX)/drivers/gpu/drm/drm_syncobj.c \
	$(LINUX)/drivers/gpu/drm/drm_sysfs.c \
	$(LINUX)/drivers/gpu/drm/drm_trace_points.c \
	$(LINUX)/drivers/gpu/drm/drm_vblank.c \
	$(LINUX)/drivers/gpu/drm/drm_vblank_work.c \
	$(LINUX)/drivers/gpu/drm/drm_vma_manager.c \
	$(LINUX)/drivers/gpu/drm/drm_writeback.c \
	$(LINUX)/drivers/gpu/drm/scheduler/sched_entity.c \
	$(LINUX)/drivers/gpu/drm/scheduler/sched_fence.c \
	$(LINUX)/drivers/gpu/drm/scheduler/sched_main.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_backup.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_bo.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_bo_util.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_bo_vm.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_device.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_execbuf_util.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_module.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_pool.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_range_manager.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_resource.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_sys_manager.c \
	$(LINUX)/drivers/gpu/drm/ttm/ttm_tt.c

# Generic kernel library helpers compiled unmodified (drivers/gpu/buddy.c
# carries the declared patch in patches/linux/). Each entry is
# <linuxu object path>:<upstream source>; the object keeps its linuxu name so
# tests and stub policy refer to one stable path.
UPSTREAM_HELPERS := \
	shims/crc16:lib/crc/crc16.c \
	shims/hdmi:drivers/video/hdmi.c \
	shims/kfifo:lib/kfifo.c \
	shims/list_sort:lib/list_sort.c \
	shims/rbtree:lib/rbtree.c \
	shims/sort:lib/sort.c \
	drm/drm_buddy:drivers/gpu/drm/drm_buddy.c \
	drm/gpu_buddy:drivers/gpu/buddy.c
