/* linuxu: SHIM (third_party/linux/include/linux/debug_locks.h) — no-op */
#ifndef __LINUX_DEBUG_LOCKS_H
#define __LINUX_DEBUG_LOCKS_H

#define debug_check_no_locks_held()	do { } while (0)
#define debug_check_no_locks_scheduled()	do { } while (0)
#define debug_check_no_locks_held_rcu()	do { } while (0)
#define debug_check_no_locks_held_sched()	do { } while (0)
#define debug_check_no_locks_held_nmi()	do { } while (0)
#define debug_check_no_locks_held_hardirq()	do { } while (0)
#define debug_check_no_locks_held_softirq()	do { } while (0)
#define debug_check_no_locks_held_atomic()	do { } while (0)
#define debug_check_no_locks_held_process()	do { } while (0)
#define debug_check_no_locks_held_task()	do { } while (0)
#define debug_check_no_locks_held_thread()	do { } while (0)
#define debug_check_no_locks_held_work()	do { } while (0)
#define debug_check_no_locks_held_timer()	do { } while (0)
#define debug_check_no_locks_held_completion()	do { } while (0)
#define debug_check_no_locks_held_mutex()	do { } while (0)
#define debug_check_no_locks_held_rmutex()	do { } while (0)
#define debug_check_no_locks_held_rwsem()	do { } while (0)
#define debug_check_no_locks_held_rwlock()	do { } while (0)
#define debug_check_no_locks_held_spinlock()	do { } while (0)
#define debug_check_no_locks_held_read_lock()	do { } while (0)
#define debug_check_no_locks_held_write_lock()	do { } while (0)
#define debug_check_no_locks_held_read_lock_bh()	do { } while (0)
#define debug_check_no_locks_held_write_lock_bh()	do { } while (0)
#define debug_check_no_locks_held_read_lock_irq()	do { } while (0)
#define debug_check_no_locks_held_write_lock_irq()	do { } while (0)
#define debug_check_no_locks_held_read_lock_irqsave()	do { } while (0)
#define debug_check_no_locks_held_write_lock_irqsave()	do { } while (0)
#define debug_check_no_locks_held_read_lock_nested()	do { } while (0)
#define debug_check_no_locks_held_write_lock_nested()	do { } while (0)
#define debug_check_no_locks_held_read_lock_irq_nested()	do { } while (0)
#define debug_check_no_locks_held_write_lock_irq_nested()	do { } while (0)
#define debug_check_no_locks_held_read_lock_irqsave_nested()	do { } while (0)
#define debug_check_no_locks_held_write_lock_irqsave_nested()	do { } while (0)
#define debug_check_no_locks_held_read_lock_nested_irq()	do { } while (0)
#define debug_check_no_locks_held_write_lock_nested_irq()	do { } while (0)
#define debug_check_no_locks_held_read_lock_nested_irqsave()	do { } while (0)
#define debug_check_no_locks_held_write_lock_nested_irqsave()	do { } while (0)
#define debug_check_no_locks_held_read_lock_nested_irqsave_nested()	do { } while (0)
#define debug_check_no_locks_held_write_lock_nested_irqsave_nested()	do { } while (0)

#endif /* __LINUX_DEBUG_LOCKS_H */
