/* linuxu: SHIM (vendor/linux/arch/x86/include/asm/intel-family.h)
 *
 * The amdgpu driver only needs this header to exist (it uses
 * INTEL_FAM6_* constants that don't gate any host path); keep the
 * family constants the vendor defines, values verbatim. */
#ifndef _ASM_X86_INTEL_FAMILY_H
#define _ASM_X86_INTEL_FAMILY_H

#define INTEL_FAM6_WESTMERE		6
#define INTEL_FAM6_NEHALEM		6
#define INTEL_FAM6_SANDYBRIDGE		6
#define INTEL_FAM6_IVYBRIDGE		6
#define INTEL_FAM6_HASWELL		6
#define INTEL_FAM6_BROADWELL		6
#define INTEL_FAM6_SKYLAKE		6
#define INTEL_FAM6_CASCADELAKE		6
#define INTEL_FAM6_ICELAKE		6
#define INTEL_FAM6_TIGERLAKE		6
#define INTEL_FAM6_ROCKETLAKE		6
#define INTEL_FAM6_ALDERLAKE		6
#define INTEL_FAM6_RAPTORLAKE		6
#define INTEL_FAM6_METEORLAKE		6
#define INTEL_FAM6_GRANITERAPIDS	6
#define INTEL_FAM6_ARROWLAKE		6
#define INTEL_FAM6_LUNARBAY		6
#define INTEL_FAM6_WESTMERE_EP		6
#define INTEL_FAM6_SAPPHIRERAPIDS	6
#define INTEL_FAM6_EMERALDRAPIDS	6
#define INTEL_FAM6_FIERYRANGE		6

#define INTEL_CPUFAMILY_BROADWELL	6
#define INTEL_CPUFAMILY_SKYLAKE		6
#define INTEL_CPUFAMILY_ICELAKE		6
#define INTEL_CPUFAMILY_TIGERLAKE	6
#define INTEL_CPUFAMILY_ROCKETLAKE	6
#define INTEL_CPUFAMILY_ALDERLAKE	6
#define INTEL_CPUFAMILY_RAPTORLAKE	6
#define INTEL_CPUFAMILY_GRANITERAPIDS	6
#define INTEL_CPUFAMILY_SAPPHIRERAPIDS	6
#define INTEL_CPUFAMILY_EMERALDRAPIDS	6
#define INTEL_CPUFAMILY_FIERYRANGE	6

/* vendor 2026 intel-family.h VFM model constants (used by amdgpu_device.c) */
#include <asm/cpu_device_id.h>
#define INTEL_TIGERLAKE		VFM_MAKE(X86_VENDOR_INTEL, 6, 0x8C)
#define INTEL_TIGERLAKE_L		VFM_MAKE(X86_VENDOR_INTEL, 6, 0x9)
#define INTEL_ROCKETLAKE		VFM_MAKE(X86_VENDOR_INTEL, 6, 0x9A)
#define INTEL_ALDERLAKE		VFM_MAKE(X86_VENDOR_INTEL, 6, 0x97)
#define INTEL_ALDERLAKE_L		VFM_MAKE(X86_VENDOR_INTEL, 6, 0x9B)
#define INTEL_RAPTORLAKE		VFM_MAKE(X86_VENDOR_INTEL, 6, 0xB7)
#define INTEL_RAPTORLAKE_P		VFM_MAKE(X86_VENDOR_INTEL, 6, 0xB6)
#define INTEL_RAPTORLAKE_S		VFM_MAKE(X86_VENDOR_INTEL, 6, 0xBF)

#endif
