/* linuxu shim: fw - in-process firmware cache behind request_firmware().
 *
 * The dext build cannot open() arbitrary paths, so request_firmware()
 * resolves names against this name->blob cache instead of /lib/firmware.
 * Nothing in the cache is device specific: every name upstream asks for is
 * looked up the same way.
 *
 * Sources, in lookup order (see linuxu/src/shims/firmware.c):
 *   1. host-provided entries: pushed through the LoadFirmware selector
 *      (fw_table_override) or fetched on demand from the user-space
 *      firmware servicer (fw_mailbox_fetch + fw_table_adopt);
 *   2. the on-demand servicer itself, when no host entry exists yet;
 *   3. the optional embedded table (fw_rodata_generated.c, generated by
 *      scripts/fw2rodata.py from whatever firmware directory the build was
 *      given; it may be empty and is never assumed to be complete);
 *   4. otherwise -ENOENT, so upstream's own optional-firmware fallbacks run
 *      exactly as on Linux.
 *
 * Thread-safety: all entry points take the table lock.  Lookups that hand
 * bytes to callers go through fw_table_snapshot()/fw_table_read_buffer(),
 * which copy mutable entries under the lock.
 */
#ifndef LINUXU_FW_TABLE_H
#define LINUXU_FW_TABLE_H

#include <stddef.h>
#include <stdint.h>

/* One firmware blob.  `blob` is either immutable embedded rodata or a
 * table-owned heap copy. */
struct fw_entry {
	const char   *name;
	const uint8_t *blob;
	size_t        size;
};

/* Add (or replace) one entry by copying its bytes.  0 on success, -1 on
 * OOM or an invalid entry. */
int  fw_table_register(const struct fw_entry *entry);

/* Take ownership of a malloc()ed blob for `name` (replacing any entry of
 * that name).  On failure the caller still owns `blob`.  0 / -1. */
int  fw_table_adopt(const char *name, uint8_t *blob, size_t size);

/* Nonzero if `name` has a host-provided (pushed or fetched) entry, as
 * opposed to only an embedded fallback or nothing at all. */
int  fw_table_has_override(const char *name);

/* Name lookup. Returns the entry, or NULL if `name` is not in the table. */
const struct fw_entry *fw_table_find(const char *name);

/* Take a stable snapshot under the table lock. Only immutable embedded
 * rodata may be borrowed; mutable entries are copied with kmalloc. The
 * caller releases *owned copies with kfree. */
int fw_table_snapshot(const char *name, int allow_rodata,
		      const uint8_t **blob, size_t *size, int *owned);

/* Copy directly into caller-owned storage under the table lock. Full loads
 * reject undersized buffers; partial loads copy at most the requested span. */
int fw_table_read_buffer(const char *name, void *buffer, size_t capacity,
			 size_t offset, int partial, size_t *copied);

/* Number of entries currently in the cache. */
size_t fw_table_count(void);

/* Name of entry `i` (for diagnostics/tests); NULL past the end. */
const char *fw_table_name_at(size_t i);

/* Verify every cached entry resolves to a non-NULL blob of at least 16
 * bytes and mark it loaded.  Idempotent.  Returns the number of entries
 * that failed (0 = all good). */
int fw_boot_load_all(void);

/* Number of entries marked loaded. */
size_t fw_table_loaded_count(void);

/* Drop all entries (test teardown; the dext keeps the cache for its whole
 * lifetime). */
void fw_table_clear(void);

/*
 * Register whatever the optional embedded table contains (rows from
 * fw_rodata_generated.c).  Host-provided entries of the same name are kept.
 * An empty embedded table is valid and returns 0.  Returns the number of
 * rows that failed to register.
 */
int fw_table_register_embedded(void);

/*
 * Host-push override channel: replace (or add) the bytes for a firmware
 * name.  Called for the LoadFirmware selector.  A subsequent
 * request_firmware() of `name` returns these bytes.  Returns 0 on success,
 * -1 on OOM/size<16, -2 on a NULL name or NULL bytes with size>0.
 */
int fw_table_override(const char *name, const uint8_t *bytes, size_t size);

#endif /* LINUXU_FW_TABLE_H */
