#!/usr/bin/env bash
# Regenerates hsa/src/signal_kernels_code.h: the signal-operation and
# signal-mailbox kernels compiled for every GPU target family the runtime can
# select at run time. One code object per LLVM generic target, plus a specific
# target wherever LLVM defines no generic family for that processor.
#
#   hsa/tools/build-signal-kernels.sh            # regenerate the header
#   AMDGPU_LLVM_BIN=/path/to/llvm/bin AMDGPU_LLD=/path/to/ld.lld hsa/tools/build-signal-kernels.sh
#
# The runtime picks the object whose ELF target is compatible with the agent's
# ISA (the agent's own processor first, then its generic family), using the
# same rules as the code-object loader. Adding a family means adding its
# target to TARGETS below, re-running this script, and nothing else.
set -euo pipefail
cd "$(dirname "$0")/../.."

# Pinned toolchain: the shipped objects were produced with LLVM 21.1.8 (the
# LLVM used by Loom). A different compiler changes the machine code and must be
# re-qualified on hardware.
if [[ -n "${AMDGPU_LLVM_BIN:-}" ]]; then
  llvm_bin="$AMDGPU_LLVM_BIN"
elif [[ -x /opt/homebrew/opt/llvm@21/bin/clang ]]; then
  llvm_bin=/opt/homebrew/opt/llvm@21/bin
else
  llvm_bin=/opt/homebrew/opt/llvm/bin
fi
if [[ -n "${AMDGPU_LLD:-}" ]]; then
  lld="$AMDGPU_LLD"
elif [[ -x /opt/homebrew/opt/lld@21/bin/ld.lld ]]; then
  lld=/opt/homebrew/opt/lld@21/bin/ld.lld
else
  lld=ld.lld
fi

# Generic families first, then processors that belong to no generic family.
# gfx908 and gfx90a have no LLVM generic target; LLVM 21 has no
# gfx12-5-generic, so gfx1250 is built as its specific processor.
TARGETS=(
  gfx9-generic
  gfx9-4-generic
  gfx10-1-generic
  gfx10-3-generic
  gfx11-generic
  gfx12-generic
  gfx908
  gfx90a
  gfx1250
)
KERNELS=(signal_operations signal_mailbox_service)

out_dir=build/signal-kernels
mkdir -p "$out_dir"
"$llvm_bin/clang" --version | head -1 > "$out_dir/toolchain.txt"
"$lld" --version | head -1 >> "$out_dir/toolchain.txt"

for target in "${TARGETS[@]}"; do
  for kernel in "${KERNELS[@]}"; do
    base="$out_dir/$kernel-$target"
    "$llvm_bin/clang" -target amdgcn-amd-amdhsa -mcpu="$target" -nogpulib \
      -mcode-object-version=6 -x cl -cl-std=CL2.0 -O2 -Ihsa/src \
      -c "hsa/src/$kernel.cl" -o "$base.o"
    "$llvm_bin/clang" -target amdgcn-amd-amdhsa -mcpu="$target" -nogpulib \
      -mcode-object-version=6 -x cl -cl-std=CL2.0 -O2 -Ihsa/src \
      -S -emit-llvm "hsa/src/$kernel.cl" -o "$base.ll"
    "$lld" -shared --no-undefined "$base.o" -o "$base.hsaco"
    "$llvm_bin/llvm-readelf" --notes "$base.hsaco" > "$base.metadata"
    "$llvm_bin/llvm-objdump" -d "$base.hsaco" > "$base.disasm"
  done
done

TARGETS="${TARGETS[*]}" KERNELS="${KERNELS[*]}" OUT_DIR="$out_dir" python3 - <<'PY'
import os, re, struct
from pathlib import Path

out = Path(os.environ['OUT_DIR'])
targets = os.environ['TARGETS'].split()
kernels = os.environ['KERNELS'].split()
kernarg = {'signal_operations': 36, 'signal_mailbox_service': 32}

def family(target):
    """The memory-model instructions a SYSTEM-scope acquire/release must emit."""
    if target.startswith('gfx12'):
        return ['global_inv scope:SCOPE_SYS', 'global_wb scope:SCOPE_SYS']
    if target.startswith('gfx11') or target.startswith('gfx10'):
        return ['buffer_gl0_inv', 'buffer_gl1_inv']
    if target in ('gfx9-4-generic',):
        return ['buffer_inv sc0 sc1', 'buffer_wbl2 sc0 sc1']
    if target == 'gfx90a':
        return ['buffer_invl2', 'buffer_wbl2']
    return ['buffer_wbinvl1_vol']

def ident(name):
    return re.sub(r'[^0-9A-Za-z]', '_', name)

lines = ['#pragma once', '#include <cstdint>', '#include <span>',
         '// Generated by hsa/tools/build-signal-kernels.sh from signal_operations.cl and',
         '// signal_mailbox_service.cl. Do not edit; re-run the script instead.']
for tool in (out / 'toolchain.txt').read_text().splitlines():
    lines.append('// ' + tool)
lines.append('namespace mac_hsa::signal_kernels {')
entries = []
for target in targets:
    wave = 64 if target.startswith('gfx9') else 32
    lines.append(f'namespace {ident(target)} {{')
    for kernel in kernels:
        base = out / f'{kernel}-{target}'
        ir = base.with_suffix('.ll').read_text()
        isa = base.with_suffix('.disasm').read_text()
        metadata = base.with_suffix('.metadata').read_text()
        assert 'syncscope(' not in ir, (target, kernel, 'non-system atomic scope')
        for operation in ('xchg', 'add', 'sub', 'and', 'or', 'xor'):
            assert 'atomicrmw ' + operation in ir, (target, kernel, operation)
        assert 'cmpxchg' in ir and 'seq_cst seq_cst' in ir, (target, kernel)
        if kernel == 'signal_mailbox_service':
            assert ' acquire,' in ir and ' release,' in ir, (target, kernel)
        for needle in family(target):
            assert needle in isa, (target, kernel, needle)
        assert '.group_segment_fixed_size: 0' in metadata, (target, kernel)
        assert '.private_segment_fixed_size: 0' in metadata, (target, kernel)
        assert f'.kernarg_segment_size: {kernarg[kernel]}' in metadata, (target, kernel)
        assert f'.wavefront_size: {wave}' in metadata, (target, kernel)
        assert f'amdgcn-amd-amdhsa--{target}' in metadata, (target, kernel)
        blob = base.with_suffix('.hsaco').read_bytes()
        flags = struct.unpack_from('<I', blob, 48)[0]
        lines.append(f'// {target} {kernel}: e_flags={flags:#010x}, {len(blob)} bytes')
        lines.append(f'inline constexpr uint8_t {kernel}[] = {{')
        lines += ['    ' + ','.join(f'0x{b:02x}' for b in blob[i:i + 24]) + ','
                  for i in range(0, len(blob), 24)]
        lines.append('};')
    lines.append('}')
    entries.append(target)
lines.append('struct CodeObjects { const char *target; std::span<const uint8_t> operations, mailbox; };')
lines.append('inline constexpr CodeObjects kCodeObjects[] = {')
for target in entries:
    n = ident(target)
    lines.append(f'    {{"{target}", {n}::signal_operations, {n}::signal_mailbox_service}},')
lines.append('};')
lines.append('}')
Path('hsa/src/signal_kernels_code.h').write_text('\n'.join(lines) + '\n')
print('wrote hsa/src/signal_kernels_code.h for:', ' '.join(entries))
PY
