#pragma once
#include "isa_target.h"
#include <cstdint>
#include <span>
#include <string>

namespace mac_hsa {
// The runtime's own GPU kernels (signal_operations.cl and
// signal_mailbox_service.cl), shipped as one code object per GPU family and
// regenerated by hsa/tools/build-signal-kernels.sh.
struct SignalKernelObjects {
    const char *target = nullptr; // the bundle entry, e.g. "gfx11-generic"
    std::span<const uint8_t> operations, mailbox;
    bool generic = false;
};
// Selects the objects for the agent's ISA with the loader's compatibility
// rules: the agent's own processor first, then its generic family. Returns
// false, with a message naming the ISA and the bundled targets, when none
// is compatible.
bool selectSignalKernels(const IsaTarget &agent, SignalKernelObjects &out, std::string *error = nullptr);
// The kernel_code_properties the signal kernels may use with AQL dispatch:
// the kernarg segment pointer (bit 3, required); on wave32 targets
// ENABLE_WAVEFRONT_SIZE32 (bit 10); and on targets without architected flat
// scratch (GFX9 before GFX9.4, GFX10) the private segment buffer user SGPRs
// (bit 0), which the packet processor loads from the queue's scratch
// descriptor. No other implicit SGPR input is set up by the dispatch paths.
constexpr uint16_t kAQLKernelPropertiesOptional = 0x401;
constexpr bool signalKernelProperties(uint16_t properties) {
    return (properties & ~kAQLKernelPropertiesOptional) == 0x008u;
}
// Every bundled target, in bundle order (diagnostics and tests).
std::span<const char *const> bundledSignalKernelTargets();
}
